<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LAB05_Bai02\LAB05_Bai02.csproj" />
    <ProjectReference Include="..\LAB05_Bai1\LAB05_Bai1.csproj" />
    <ProjectReference Include="..\LAB05_BAI4\LAB05_BAI4.csproj" />
    <ProjectReference Include="..\LAB5_Bai3\LAB5_Bai3.csproj" />
  </ItemGroup>

</Project>